services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bedrock-chatbot-web
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - ${USERPROFILE}/.aws:/root/.aws:ro # Mount AWS credentials (Read-Only)
    environment:
      - WATCHPACK_POLLING=true
      - AWS_PROFILE=BedrockDevUser-hyebom
      - AWS_SDK_LOAD_CONFIG=1
    # Install deps and start dev server on 0.0.0.0
    command: sh -c "npm install && npm run dev -- -H 0.0.0.0"
